fix issues

diff --git a/.github/workflows/tag_template.yml b/.github/workflows/tag_template.yml
--- a/.github/workflows/tag_template.yml
+++ b/.github/workflows/tag_template.yml
@@ -29,16 +29,24 @@ jobs:
       - name: Version check
         run: |
           # Convert VERSION_1 and VERSION_2 to positional variables
-          new_tag=${{ inputs.VERSION }}
-          last_tag=${{ env.latest_tag || '0.0.0' }}
+          NEW_TAG=${{ inputs.VERSION }}
+          LAST_TAG=${{ env.latest_tag || 'v0.0.0' }}
+
+          # Extract the 'v' prefix
+          NEW_TAG_NO_V="${NEW_TAG#v}"
+          LAST_TAG_NO_V="${LAST_TAG#v}"
+
+          # Validate if valid SemVer format
+          if ! [[ "$NEW_TAG_NO_V" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: New tag $NEW_TAG is not a valid SemVer!"
+            exit 1
+          fi
 
           # Compare versions
-          compare_versions() {
-            if [[ $(echo -e "$new_tag\n$last_tag" | sort -V | head -n1) == "$last_tag" ]] && [[ "$new_tag" != "$last_tag" ]]; then
-              echo "Last tag $last_tag is higher than New tag $new_tag. Please update your tag variable"
-              exit 1
-            fi
-          }
+          if [[ "$(echo -e "$NEW_TAG_NO_V\n$LAST_TAG_NO_V" | sort -V | head -n1)" != "$LAST_TAG_NO_V" ]]; then
+            echo "Error: New tag $NEW_TAG is not higher than last tag $LAST_TAG!"
+            exit 1
+          fi
 
   push_tag:
     if: github.ref == 'refs/heads/master'
